import io
import json
import pickle
import datetime

import streamlit as st
import pandas as pd

from components.cards import section_title, section_caption, empty_state, info_card


def _predictions_csv(results):
    if results["type"] == "regression":
        out = pd.DataFrame({"actual": results["y_test"], "predicted": results["y_pred"]})
    elif results["type"] == "classification":
        out = pd.DataFrame({"confusion_matrix_label": results["labels"]})
    elif results["type"] == "clustering":
        out = pd.DataFrame(results["X"], columns=results["feature_names"])
        out["cluster"] = results["labels"]
    else:
        out = pd.DataFrame(results["components"], columns=["PC1", "PC2"])
    buf = io.StringIO()
    out.to_csv(buf, index=False)
    return buf.getvalue()


def _metrics_report(results):
    report = {
        "algorithm": results["algorithm"],
        "task_type": results["type"],
        "generated_at": datetime.datetime.now().isoformat(),
    }
    if "metrics" in results:
        report["metrics"] = results["metrics"]
    if "train_time" in results:
        report["train_time_seconds"] = results["train_time"]
    if "predict_time" in results:
        report["predict_time_seconds"] = results["predict_time"]
    return json.dumps(report, indent=2, default=str)


def _build_pdf(results):
    from reportlab.lib.pagesizes import letter
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib import colors

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("MyML Lab — Model Summary Report", styles["Title"]))
    story.append(Spacer(1, 10))
    story.append(Paragraph(f"Algorithm: {results['algorithm']}", styles["Normal"]))
    story.append(Paragraph(f"Task Type: {results['type'].title()}", styles["Normal"]))
    story.append(Paragraph(f"Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}", styles["Normal"]))
    story.append(Spacer(1, 16))

    if "metrics" in results:
        story.append(Paragraph("Performance Metrics", styles["Heading2"]))
        data = [["Metric", "Value"]] + [[k, f"{v:.4f}" if isinstance(v, float) else str(v)] for k, v in results["metrics"].items()]
        table = Table(data, hAlign="LEFT")
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#FF2E88")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
        ]))
        story.append(table)
        story.append(Spacer(1, 16))

    story.append(Paragraph("Timing", styles["Heading2"]))
    timing_lines = []
    if "train_time" in results:
        timing_lines.append(f"Training Time: {results['train_time']:.4f} s")
    if "predict_time" in results:
        timing_lines.append(f"Prediction Time: {results['predict_time']:.4f} s")
    for line in timing_lines:
        story.append(Paragraph(line, styles["Normal"]))

    story.append(Spacer(1, 16))
    story.append(Paragraph("Generated by MyML Lab — a machine learning library built from scratch with NumPy.", styles["Italic"]))

    doc.build(story)
    buf.seek(0)
    return buf.getvalue()


def render():
    section_title("Reports", "📄")
    section_caption("Export your latest trained model, predictions, and a shareable summary report.")

    results = st.session_state.get("results")
    if not results:
        empty_state("Train a model first to unlock downloadable reports.", "📄")
        return

    info_card(results["algorithm"], f"Task type: {results['type'].title()}", badge="Ready to export", badge_type="green")
    st.markdown("<br>", unsafe_allow_html=True)

    c1, c2, c3, c4 = st.columns(4)

    with c1:
        st.download_button(
            "⬇️ Predictions CSV",
            data=_predictions_csv(results),
            file_name=f"myml_predictions_{results['type']}.csv",
            mime="text/csv",
            use_container_width=True,
        )

    with c2:
        st.download_button(
            "⬇️ Metrics Report",
            data=_metrics_report(results),
            file_name=f"myml_metrics_{results['type']}.json",
            mime="application/json",
            use_container_width=True,
        )

    with c3:
        model = results.get("model")
        model_bytes = pickle.dumps(results)
        st.download_button(
            "⬇️ Trained Model",
            data=model_bytes,
            file_name=f"myml_model_{results['algorithm'].replace(' ', '_').lower()}.pkl",
            mime="application/octet-stream",
            use_container_width=True,
        )

    with c4:
        try:
            pdf_bytes = _build_pdf(results)
            st.download_button(
                "⬇️ PDF Summary",
                data=pdf_bytes,
                file_name=f"myml_summary_{results['type']}.pdf",
                mime="application/pdf",
                use_container_width=True,
            )
        except Exception as e:
            st.error(f"PDF generation unavailable: {e}")
